# Generated by Django 4.2.5 on 2023-09-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userdata2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
