# Generated by Django 4.2.5 on 2023-09-21 10:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_delete_userdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserData2',
            new_name='UserData',
        ),
    ]
