# Generated by Django 4.2.5 on 2023-09-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_userdata2_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='Fullname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='UserAvatar',
            field=models.ImageField(null=True, upload_to='./templates/main/DBimages'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='UserGitLink',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='UserGroup',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
