# Generated by Django 4.2.5 on 2023-09-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_userdata_fullname_alter_userdata_useravatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='id',
        ),
        migrations.AddField(
            model_name='userdata',
            name='Usernick',
            field=models.CharField(default='ERROR', max_length=20, primary_key=True, serialize=False),
        ),
    ]
