# Generated by Django 4.2.5 on 2023-09-26 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_remove_userdata_id_userdata_usernick'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=100)),
                ('ProjectDescription', models.TextField(blank=True, null=True)),
                ('ProjectLink', models.URLField(max_length=100)),
                ('ProjectDate', models.DateTimeField(auto_now_add=True)),
                ('UserF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
