# Generated by Django 4.2.5 on 2023-09-26 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='UserF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userdata'),
        ),
    ]
