# Generated by Django 4.2.5 on 2023-09-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_projects_userf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='UserF',
            new_name='Usernick',
        ),
    ]
